# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: master_service_discovery.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import common_pb2 as common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='master_service_discovery.proto',
  package='milvus.proto.master',
  syntax='proto3',
  serialized_options=b'Z3github.com/milvus-io/milvus/internal/proto/masterpb',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1emaster_service_discovery.proto\x12\x13milvus.proto.master\x1a\x0c\x63ommon.proto\"\x10\n\x0eGetInfoRequest\"\xa5\x01\n\x0fGetInfoResponse\x12+\n\x06status\x18\x01 \x01(\x0b\x32\x1b.milvus.proto.common.Status\x12\x31\n\x05nodes\x18\x02 \x03(\x0b\x32\".milvus.proto.master.ProxyNodeInfo\x12\x32\n\x07metrics\x18\x03 \x03(\x0b\x32!.milvus.proto.common.KeyValuePair\"+\n\rProxyNodeInfo\x12\x0c\n\x04host\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\r2r\n\x18ServiceDiscoveryProvider\x12V\n\x07GetInfo\x12#.milvus.proto.master.GetInfoRequest\x1a$.milvus.proto.master.GetInfoResponse\"\x00\x42\x35Z3github.com/milvus-io/milvus/internal/proto/masterpbb\x06proto3'
  ,
  dependencies=[common__pb2.DESCRIPTOR,])




_GETINFOREQUEST = _descriptor.Descriptor(
  name='GetInfoRequest',
  full_name='milvus.proto.master.GetInfoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=85,
)


_GETINFORESPONSE = _descriptor.Descriptor(
  name='GetInfoResponse',
  full_name='milvus.proto.master.GetInfoResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='milvus.proto.master.GetInfoResponse.status', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='nodes', full_name='milvus.proto.master.GetInfoResponse.nodes', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='metrics', full_name='milvus.proto.master.GetInfoResponse.metrics', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=88,
  serialized_end=253,
)


_PROXYNODEINFO = _descriptor.Descriptor(
  name='ProxyNodeInfo',
  full_name='milvus.proto.master.ProxyNodeInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='host', full_name='milvus.proto.master.ProxyNodeInfo.host', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='port', full_name='milvus.proto.master.ProxyNodeInfo.port', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=255,
  serialized_end=298,
)

_GETINFORESPONSE.fields_by_name['status'].message_type = common__pb2._STATUS
_GETINFORESPONSE.fields_by_name['nodes'].message_type = _PROXYNODEINFO
_GETINFORESPONSE.fields_by_name['metrics'].message_type = common__pb2._KEYVALUEPAIR
DESCRIPTOR.message_types_by_name['GetInfoRequest'] = _GETINFOREQUEST
DESCRIPTOR.message_types_by_name['GetInfoResponse'] = _GETINFORESPONSE
DESCRIPTOR.message_types_by_name['ProxyNodeInfo'] = _PROXYNODEINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetInfoRequest = _reflection.GeneratedProtocolMessageType('GetInfoRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETINFOREQUEST,
  '__module__' : 'master_service_discovery_pb2'
  # @@protoc_insertion_point(class_scope:milvus.proto.master.GetInfoRequest)
  })
_sym_db.RegisterMessage(GetInfoRequest)

GetInfoResponse = _reflection.GeneratedProtocolMessageType('GetInfoResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETINFORESPONSE,
  '__module__' : 'master_service_discovery_pb2'
  # @@protoc_insertion_point(class_scope:milvus.proto.master.GetInfoResponse)
  })
_sym_db.RegisterMessage(GetInfoResponse)

ProxyNodeInfo = _reflection.GeneratedProtocolMessageType('ProxyNodeInfo', (_message.Message,), {
  'DESCRIPTOR' : _PROXYNODEINFO,
  '__module__' : 'master_service_discovery_pb2'
  # @@protoc_insertion_point(class_scope:milvus.proto.master.ProxyNodeInfo)
  })
_sym_db.RegisterMessage(ProxyNodeInfo)


DESCRIPTOR._options = None

_SERVICEDISCOVERYPROVIDER = _descriptor.ServiceDescriptor(
  name='ServiceDiscoveryProvider',
  full_name='milvus.proto.master.ServiceDiscoveryProvider',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=300,
  serialized_end=414,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetInfo',
    full_name='milvus.proto.master.ServiceDiscoveryProvider.GetInfo',
    index=0,
    containing_service=None,
    input_type=_GETINFOREQUEST,
    output_type=_GETINFORESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SERVICEDISCOVERYPROVIDER)

DESCRIPTOR.services_by_name['ServiceDiscoveryProvider'] = _SERVICEDISCOVERYPROVIDER

# @@protoc_insertion_point(module_scope)
